name: 'Build & test documentation'

on:
    push:
        branches:
            - master
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    build:
        permissions:
          # Give the default GITHUB_TOKEN write permission to commit and push the
          # added or changed files to the repository.
          contents: write

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8]

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v3
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install php-cs-fixer
                run: composer require friendsofphp/php-cs-fixer --dev
            -   name: Run PHP CS Fixer
                run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php -v --show-progress=dots
            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: PHP CS Fixes
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            -   name: Run build
                run: |
                    mkdocs build --strict

    vale-check:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            -   uses: actions/checkout@v3
            -   name: Get Vale.sh configs
                env:
                    TOKEN: ${{ secrets.EZROBOT_PAT }}
                run: |
                    curl -H "Authorization: token $TOKEN" -L https://github.com/ibexa/vale-styles/archive/refs/heads/main.zip -o vale.zip
                    unzip vale.zip
                    rm vale.zip
                    mv vale-styles-main/* vale-styles-main/.vale.ini .
            -   name: Run Vale.sh
                uses: errata-ai/vale-action@reviewdog
                with:
                  reporter: github-check
                  filter_mode: added

    code-samples-inclusion-check:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            -   name: Checkout source branch (head_ref)
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}
            -   name: Log source branch code_samples usage
                id: source
                run: |
                    git 
                    echo 'CODE_SAMPLE_USAGE<<CODE_SAMPLE_USAGE_DELIMITER'
                    tools/code_samples/code_samples_usage.php $GITHUB_BASE_REF $GITHUB_HEAD_REF
                    echo 'CODE_SAMPLE_USAGE_DELIMITER' > "$GITHUB_OUTPUT"
            -   name: Checkout target branch (base_ref)
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.base_ref }}
            -   name: Log target branch code_samples usage
                id: target
                run: |
                    echo 'CODE_SAMPLE_USAGE<<CODE_SAMPLE_USAGE_DELIMITER'
                    tools/code_samples/code_samples_usage.php $GITHUB_BASE_REF $GITHUB_HEAD_REF
                    echo 'CODE_SAMPLE_USAGE_DELIMITER' > "$GITHUB_OUTPUT"
            -   name: Compare code_samples usages and prepare for output
                id: diff
                env:
                    CODE_SAMPLE_USAGE_SOURCE: ${{ steps.source.outputs.CODE_SAMPLE_USAGE }}
                    CODE_SAMPLE_USAGE_TARGET: ${{ steps.target.outputs.CODE_SAMPLE_USAGE }}
                run: |
                    echo 'CODE_SAMPLE_USAGE<<CODE_SAMPLE_USAGE_DELIMITER'
                    diff --side-by-side --expand-tabs --width 350 <(echo $CODE_SAMPLE_USAGE_SOURCE) <(echo $CODE_SAMPLE_USAGE_TARGET) | sed 's/`/\`'
                    echo 'CODE_SAMPLE_USAGE_DELIMITER' > "$GITHUB_OUTPUT"
            -   name: Display code_samples usage comparison
                env:
                    CODE_SAMPLE_USAGE_DIFF: ${{ steps.diff.outputs.CODE_SAMPLE_USAGE }}
                uses: actions/github-script@v6
                with:
                    script: |
                        github.rest.issues.createComment({
                            issue_number: context.issue.number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            body: process.env.CODE_SAMPLE_USAGE_DIFF
                        })
