name: 'Build & test documentation'

on:
    push:
        branches:
            - master
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    build:
        permissions:
          # Give the default GITHUB_TOKEN write permission to commit and push the
          # added or changed files to the repository.
          contents: write

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8]

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v3
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install php-cs-fixer
                run: composer require friendsofphp/php-cs-fixer --dev
            -   name: Run PHP CS Fixer
                run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php -v --show-progress=dots
            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: PHP CS Fixes
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            -   name: Run build
                run: |
                    mkdocs build --strict

    vale-check:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            -   uses: actions/checkout@v3
            -   name: Get Vale.sh configs
                env:
                    TOKEN: ${{ secrets.EZROBOT_PAT }}
                run: |
                    curl -H "Authorization: token $TOKEN" -L https://github.com/ibexa/vale-styles/archive/refs/heads/main.zip -o vale.zip
                    unzip vale.zip
                    rm vale.zip
                    mv vale-styles-main/* vale-styles-main/.vale.ini .
            -   name: Run Vale.sh
                uses: errata-ai/vale-action@reviewdog
                with:
                  reporter: github-check
                  filter_mode: added

    code-samples-inclusion-check:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            -   name: List modified files
                id: list
                run: |
                    URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
                    echo 'CODE_SAMPLE_USAGE<<CODE_SAMPLE_USAGE_DELIMITER' >> "$GITHUB_OUTPUT"
                    curl -s -X GET -G $URL | jq -r '.[] | .filename' | grep '^code_samples/' | tr '\n' ' ' >> "$GITHUB_OUTPUT"
                    echo '' >> "$GITHUB_OUTPUT"
                    echo 'CODE_SAMPLE_USAGE_DELIMITER' >> "$GITHUB_OUTPUT"
            -   name: Checkout source branch (head_ref)
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}
            -   name: Log source branch code_samples usage
                run: php tools/code_samples/code_samples_usage.php ${{ steps.list.outputs.CODE_SAMPLE_USAGE }} > $HOME/code_samples_usage_source.txt
            -   name: Checkout target branch (base_ref)
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.base_ref }}
            -   name: Log target branch code_samples usage
                run: |
                    git checkout origin/${{ github.head_ref }} -- tools/code_samples/code_samples_usage.php
                    php tools/code_samples/code_samples_usage.php ${{ steps.list.outputs.CODE_SAMPLE_USAGE }} > $HOME/code_samples_usage_target.txt
            -   name: Compare code_samples usages (diff)
                # diff returns 1 if there is a difference, this is normal but seen as an error by the job.
                continue-on-error: true
                run: |
                    source_length=`wc -l < $HOME/code_samples_usage_source.txt`
                    target_length=`wc -l < $HOME/code_samples_usage_target.txt`
                    diff -U $(( source_length > target_length ? source_length : target_length )) $HOME/code_samples_usage_target.txt $HOME/code_samples_usage_source.txt > $HOME/code_samples_usage.diff
            -   name: Convert code_samples usages differences (diff2html)
                run: |
                    npm install -g diff2html-cli
                    diff2html -f html -s side -o stdout -i file -- $HOME/code_samples_usage.diff > $HOME/code_samples_usage.diff.html
            -   name: Upload code_samples usages differences artifact
                id: artifact
                uses: actions/upload-artifact@v4
                with:
                    name: code_samples_usage.diff.html
                    path: ~/code_samples_usage.diff.html
            -   name: Find Comment
                uses: peter-evans/find-comment@v3
                id: find-comment
                with:
                    issue-number: ${{ github.event.pull_request.number }}
                    comment-author: 'github-actions[bot]'
                    body-includes: 'code_samples/ change report'
            -   name: Create or update comment
                uses: peter-evans/create-or-update-comment@v4
                with:
                    comment-id: ${{ steps.find-comment.outputs.comment-id }}
                    issue-number: ${{ github.event.pull_request.number }}
                    body: |
                        # code_samples/ change report
                        ${{ steps.artifact.outputs.artifact-url }}
                    edit-mode: replace
